version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-financas
    environment:
      POSTGRES_USER: root      
      POSTGRES_PASSWORD: root  
      POSTGRES_DB: gerenciador_financas    
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
